//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2001: Codable {

    public var gernes: [InlineResponse2001Gernes]?

    public init(gernes: [InlineResponse2001Gernes]? = nil) {
        self.gernes = gernes
    }

}
