//
// InlineResponse2001Gernes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2001Gernes: Codable {

    public var name: String?
    public var id: Int?

    public init(name: String? = nil, id: Int? = nil) {
        self.name = name
        self.id = id
    }

}
