//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2001: Codable {

    public var genres: [Genre]?

    public init(genres: [Genre]? = nil) {
        self.genres = genres
    }

}
