//
// InlineResponse2002.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2002: Codable {

    public var movie: [Movie]?

    public init(movie: [Movie]? = nil) {
        self.movie = movie
    }

}
