//
// MovieBelongsToCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MovieBelongsToCollection: Codable {

    public var id: Int?
    public var name: String?
    public var posterPath: String?
    public var backdropPath: String?

    public init(id: Int? = nil, name: String? = nil, posterPath: String? = nil, backdropPath: String? = nil) {
        self.id = id
        self.name = name
        self.posterPath = posterPath
        self.backdropPath = backdropPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case posterPath = "poster_path"
        case backdropPath = "backdrop_path"
    }

}
