//
// ProductionCountry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductionCountry: Codable {

    public var iso31661: String?
    public var name: String?

    public init(iso31661: String? = nil, name: String? = nil) {
        self.iso31661 = iso31661
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iso31661 = "iso_3166_1"
        case name
    }

}
