//
// ProductionCompany.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductionCompany: Codable {

    public var name: String?
    public var id: Int?
    public var logoPath: String?
    public var originCountry: String?

    public init(name: String? = nil, id: Int? = nil, logoPath: String? = nil, originCountry: String? = nil) {
        self.name = name
        self.id = id
        self.logoPath = logoPath
        self.originCountry = originCountry
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case id
        case logoPath = "logo_path"
        case originCountry = "origin_country"
    }

}
