//
// SpokenLanguage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpokenLanguage: Codable {

    public var iso6391: String?
    public var name: String?

    public init(iso6391: String? = nil, name: String? = nil) {
        self.iso6391 = iso6391
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iso6391 = "iso_639_1"
        case name
    }

}
